### ISSUE TITLE
Error with eq_myodoo_backend

### ISSUE THREAD

**Issue by alex9434** [equitania/v8-server#1]
I tried to install myodoo backed in OCB 8.0 on ubuntu 16.04. However, I got the following error message:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openerp/http.py", line 546, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/dist-packages/openerp/http.py", line 583, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/dist-packages/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/http.py", line 316, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp/http.py", line 812, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp/http.py", line 412, in response_wrap
    response = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/local/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/addons/base/module/module.py", line 496, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/local/lib/python2.7/dist-packages/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/lib/python2.7/dist-packages/openerp/modules/loading.py", line 354, in load_modules
    loaded_modules, update_module)
  File "/usr/local/lib/python2.7/dist-packages/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/lib/python2.7/dist-packages/openerp/modules/loading.py", line 176, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/local/lib/python2.7/dist-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/lib/python2.7/dist-packages/openerp/tools/convert.py", line 897, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/lib/python2.7/dist-packages/openerp/tools/convert.py", line 983, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/openerp/tools/convert.py", line 849, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/local/lib/python2.7/dist-packages/openerp/tools/convert.py", line 823, in _tag_template
    return self._tag_record(cr, record, data_node)
  File "/usr/local/lib/python2.7/dist-packages/openerp/tools/convert.py", line 759, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_model.py", line 1023, in _update
    model_obj.write(cr, uid, [res_id], values, context=context)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_ui_view.py", line 281, in write
    context)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/odoo_addons/connector/producer.py", line 64, in write
    result = write_original(self, vals)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/models.py", line 3811, in write
    self._write(old_vals)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, *args, **old_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/models.py", line 3990, in _write
    recs._validate_fields(vals)
  File "/usr/local/lib/python2.7/dist-packages/openerp/api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openerp/models.py", line 1275, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//div[@class='page']/div[@id='informations']">' cannot be located in parent view

Error context:
View `report_saleorder_validity_date`
[view_id: 1024, xml_id: website_quote.report_saleorder_validity_date, model: n/a, parent_id: 590]" while parsing None:777, near
<t t-name="sale.report_saleorder_document">
			<t t-call="equitania.external_layout_sale_order">
				<t t-call="equitania.report_saleorder_data"/>
			</t>
		</t>

**Comment by eqms** [comment]
Do you update your system with the parameter `-u all`
On end of this article I explain how to: [WIKI](https://equitania.atlassian.net/wiki/spaces/MW/pages/56081725/MyOdoo+auf+Synology+installieren)

**Comment by alex9434** [comment]
Unfortunately I still have the error after the update. Additionally I got the following warnings when doing the update:

2018-09-01 10:28:12,930 1758 WARNING xxx openerp.modules.loading: Model eq.product.sales.data.master is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,931 1758 WARNING xxx openerp.modules.loading: Model eq.product.sales.data is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,932 1758 WARNING xxx openerp.modules.loading: Model eq.product.analysis.data.master is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,932 1758 WARNING xxx openerp.modules.loading: Model eq.product.analysis.data is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,933 1758 WARNING xxx openerp.modules.loading: Model eq.date.done.change is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,933 1758 WARNING xxx openerp.modules.loading: Model eq_multy_assign_product_no is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,934 1758 WARNING xxx openerp.modules.loading: Model equitania.product.analysis.report.wiz is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,934 1758 WARNING xxx openerp.modules.loading: Model equitania.product.sales.report.wiz is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,935 1758 WARNING xxx openerp.modules.loading: Model eq.product.select.case.section.wiz is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,935 1758 WARNING xxx openerp.modules.loading: Model eq_list.print.wiz is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,935 1758 WARNING xxx openerp.modules.loading: Model eq_buffer_order_line_list is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,936 1758 WARNING xxx openerp.modules.loading: Model eq_install_func is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,936 1758 WARNING xxx openerp.modules.loading: Model eq_pricelist_item_search is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,936 1758 WARNING xxx openerp.modules.loading: Model eq.delivery.conditions is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,937 1758 WARNING xxx openerp.modules.loading: Model eq.lead.referred is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,937 1758 WARNING xxx openerp.modules.loading: Model eq_open_sale_order_line is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,937 1758 WARNING xxx openerp.modules.loading: Model eq_info_optional is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,938 1758 WARNING xxx openerp.modules.loading: Model sale_layout.category is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,938 1758 WARNING xxx openerp.modules.loading: Model report.account.report_invoice is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,938 1758 WARNING xxx openerp.modules.loading: Model report.purchase.report_purchaseorder is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,939 1758 WARNING xxx openerp.modules.loading: Model report.purchase.report_purchasequotation is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,939 1758 WARNING xxx openerp.modules.loading: Model report.sale.report_saleorder is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,939 1758 WARNING xxx openerp.modules.loading: Model report.equitania.report_open_sale_order_line is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,940 1758 WARNING xxx openerp.modules.loading: Model report.stock.report_picking is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,940 1758 WARNING xxx openerp.modules.loading: Model report.equitania.eq_report_stockpicking_return is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,941 1758 WARNING xxx openerp.modules.loading: Model report.equitania.eq_product_sales_report is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,941 1758 WARNING xxx openerp.modules.loading: Model report.equitania.eq_product_analysis_report is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,941 1758 WARNING xxx openerp.modules.loading: Model eq_report_helper is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,942 1758 WARNING xxx openerp.modules.loading: Model product.template.standard_price_history is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,942 1758 WARNING xxx openerp.modules.loading: Model eq.clean.data is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,942 1758 WARNING xxx openerp.modules.loading: Model basemodel.extend is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)
2018-09-01 10:28:12,943 1758 WARNING xxx openerp.modules.loading: Model eq.address.search is declared but cannot be loaded! (Perhaps a module was partially removed or renamed)

**Comment by alex9434** [comment]
I have switched the installation from OCB to equitania/v8-server and now the backend theme is working. I am closing this
